Repository micronaut-projects/micronaut-micrometer, pull requests merged in 2020-08, with the labels that each got.

#123 Dependency upgrades
  micrometer-registry-ganglia/build.gradle
Labels: type: dependency-upgrade

#125 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade

#127 [micrometer] Update common files for branch 1.2.x
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#126 [micrometer] Update common files for branch master
  README.md
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#129 [micrometer] Update common files for branch master
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
Labels: relates-to: build

#130 [micrometer] Update common files for branch 1.2.x
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
Labels: relates-to: build

#137 Doc: Release History section
  src/main/docs/guide/introduction.adoc
  src/main/docs/guide/releaseHistory.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#138 Dependency upgrades
  build.gradle
Labels: type: dependency-upgrade

#140 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade

#141 [micrometer] Update common files for branch master
  .github/workflows/release-notes.yml
Labels: relates-to: build

#142 [micrometer] Update common files for branch 2.1.x
  .github/workflows/release-notes.yml
Labels: relates-to: build
