Repository micronaut-projects/micronaut-micrometer, pull requests merged in 2020-12, with the labels that each got.

#181 [micrometer] Update common files for branch master
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#185 [micrometer] Update common files for branch master
  MAINTAINING.md
Labels: relates-to: build

#190 build: github actions MANTAINING.md
  .github/workflows/release-notes.yml
  MAINTAINING.md
Labels: relates-to: build

#191 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade

#193 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade

#196 ci: downgrade github action create-pull-request to 3.5.1
  .github/workflows/dependency-update.yml
Labels: relates-to: build

#195 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade

#199 [micrometer] Update common files for branch master
  .github/workflows/gradle.yml
Labels: relates-to: build

#202 Update gradle and maven dependencies
  src/main/docs/guide/metricsEndpoint.adoc
Labels: type: docs

#204 [micrometer] Update common files for branch master
  .github/workflows/dependency-update.yml
Labels: relates-to: build
