Repository micronaut-projects/micronaut-micrometer, pull requests merged in 2021-02, with the labels that each got.

#212 [micrometer] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#221 Dependency upgrades
  build.gradle
Labels: type: dependency-upgrade

#226 [micrometer] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#229 [micrometer] Update common files for branch master
  .github/workflows/bintray-publish.yml
  .github/workflows/central-sync.yml
  .github/workflows/dependency-update.yml
  .github/workflows/gradle.yml
  .github/workflows/release.yml
  MAINTAINING.md
Labels: relates-to: build

#227 Fix configurers logic
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/aggregator/CompositeMeterRegistryConfigurer.java
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/aggregator/MeterRegistryConfigurer.java
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/micrometer/MeterRegistryFactory.java
  micrometer-core/src/test/groovy/io/micronaut/configuration/metrics/management/endpoint/FilteredMetricsEndpointSpec.groovy
  micrometer-core/src/test/groovy/io/micronaut/configuration/metrics/management/endpoint/MetricsEndpointSpec.groovy
  micrometer-core/src/test/groovy/io/micronaut/docs/SimpleMeterRegistryConfigurer.java
Labels: type: breaking

#231 [micrometer] Update common files for branch master
  .github/workflows/central-sync.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#233 [micrometer] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#235 [micrometer] Update common files for branch master
  .github/workflows/publish-snapshot.yml
Labels: relates-to: build
