Repository micronaut-projects/micronaut-micrometer, pull requests merged in 2023-03, with the labels that each got.

#511 Never use user input for web metrics
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/ClientRequestMetricRegistryFilter.java
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/ServerRequestMeterRegistryFilter.java
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/WebMetricsPublisher.java
  micrometer-core/src/test/groovy/io/micronaut/configuration/metrics/binder/web/HttpMetricsSpec.groovy
Labels: type: bug

#512 [micrometer] Update common files for branch master
  .github/workflows/gradle.yml
Labels: relates-to: build

#412 Add a binder to count micrometer retries
  micrometer-core/build.gradle
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/retry/RetryMetricsBinder.java
  micrometer-core/src/test/groovy/io/micronaut/configuration/metrics/binder/retry/RetryMetricsBinderSpec.groovy
Labels: type: enhancement

#519 use Milestones
  .github/workflows/gradle.yml
  .github/workflows/release.yml
  buildSrc/build.gradle
  gradle/libs.versions.toml
  test-suite/micronaut-serialization/build.gradle
Labels: relates-to: build

#521 Stop using extra plugins in the micrometer-bom
  buildSrc/src/main/groovy/io.micronaut.build.internal.micrometer-base.gradle
  gradle.properties
  micrometer-bom/build.gradle
Labels: relates-to: build

#518 ci: .gitAttributes sync
  .gitattributes
Labels: relates-to: build
