Repository micronaut-projects/micronaut-micrometer, pull requests merged in 2023-07, with the labels that each got.

#580 [micrometer] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#587 Micrometer to Core 4.0.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#585 Micrometer Observation Support
  gradle.properties
  gradle/libs.versions.toml
  micrometer-annotation/src/main/java/io/micronaut/micrometer/annotation/processing/ObservedAnnotationMapper.java
  micrometer-annotation/src/main/resources/META-INF/services/io.micronaut.inject.annotation.AnnotationMapper
  micrometer-annotation/src/test/groovy/io/micronaut/micrometer/annotation/processing/AnnotationMappingSpec.groovy
  micrometer-annotation/src/test/groovy/io/micronaut/micrometer/annotation/processing/GroovyAnnotationMappingSpec.groovy
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/ClientRequestMetricRegistryFilter.java
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/ServerRequestMeterRegistryFilter.java
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/WebMetricsClientCondition.java
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/WebMetricsServerCondition.java
  micrometer-observation-http/build.gradle
  micrometer-observation-http/src/main/java/io/micronaut/micrometer/observation/http/AbstractObservationFilter.java
  micrometer-observation-http/src/main/java/io/micronaut/micrometer/observation/http/ObservationHttpExclusionsConfiguration.java
  micrometer-observation-http/src/main/java/io/micronaut/micrometer/observation/http/client/ObservationClientFilter.java
  micrometer-observation-http/src/main/java/io/micronaut/micrometer/observation/http/client/instrumentation/ClientHttpObservationDocumentation.java
  micrometer-observation-http/src/main/java/io/micronaut/micrometer/observation/http/client/instrumentation/ClientRequestObservationContext.java
  micrometer-observation-http/src/main/java/io/micronaut/micrometer/observation/http/client/instrumentation/ClientRequestObservationConvention.java
  micrometer-observation-http/src/main/java/io/micronaut/micrometer/observation/http/client/instrumentation/DefaultClientRequestObservationConvention.java
  micrometer-observation-http/src/main/java/io/micronaut/micrometer/observation/http/server/ObservationServerFilter.java
  micrometer-observation-http/src/main/java/io/micronaut/micrometer/observation/http/server/instrumentation/DefaultServerRequestObservationConvention.java
  micrometer-observation-http/src/main/java/io/micronaut/micrometer/observation/http/server/instrumentation/ServerHttpObservationDocumentation.java
  micrometer-observation-http/src/main/java/io/micronaut/micrometer/observation/http/server/instrumentation/ServerRequestObservationContext.java
  micrometer-observation-http/src/main/java/io/micronaut/micrometer/observation/http/server/instrumentation/ServerRequestObservationConvention.java
  micrometer-observation-http/src/test/groovy/io/micronaut/micrometer/observation/FilterCreationSpec.groovy
  micrometer-observation-http/src/test/groovy/io/micronaut/micrometer/observation/ObservationHttpSpec.groovy
  micrometer-observation/build.gradle
  micrometer-observation/src/main/java/io/micronaut/micrometer/observation/ContextRegistryConfigurer.java
  micrometer-observation/src/main/java/io/micronaut/micrometer/observation/DefaultObservedFactory.java
  micrometer-observation/src/main/java/io/micronaut/micrometer/observation/ObservationHandlerGrouping.java
  micrometer-observation/src/main/java/io/micronaut/micrometer/observation/ObservationHandlerGroupingClass.java
  micrometer-observation/src/main/java/io/micronaut/micrometer/observation/ObservationPropagationContext.java
  micrometer-observation/src/main/java/io/micronaut/micrometer/observation/ObservationProperties.java
  micrometer-observation/src/main/java/io/micronaut/micrometer/observation/interceptor/ObservedInterceptor.java
  micrometer-observation/src/main/java/io/micronaut/micrometer/observation/utils/ObservedReactorPropagation.java
  micrometer-observation/src/test/groovy/io/micronaut/micrometer/observation/DefaultObservedFactorySpec.groovy
  micrometer-observation/src/test/groovy/io/micronaut/micrometer/observation/ObservationHandlerGroupingSpec.groovy
  micrometer-observation/src/test/groovy/io/micronaut/micrometer/observation/annotation/ObservationAnnotationSpec.groovy
  micrometer-observation/src/test/java/io/micronaut/micrometer/observation/annotation/ObservedTarget.java
  settings.gradle
Labels: type: enhancement

#597 [micrometer] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build
