Repository micronaut-projects/micronaut-micrometer, pull requests merged in 2023-11, with the labels that each got.

#619 add missing documentation for micrometer observation module
  src/main/docs/guide/observation.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#625 [micrometer] Update common files for branch master
  .github/workflows/release.yml
  .gitignore
  MAINTAINING.md
  SECURITY.md
Labels: relates-to: build

#626 prevent unmatched urls to pollute metrics
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/ServerRequestMeterRegistryFilter.java
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/WebMetricsPublisher.java
  micrometer-core/src/test/groovy/io/micronaut/configuration/metrics/NotAcceptableRouteWithPathVariableDoesNotPolluteMetricsSpec.groovy
Labels: type: bug
