Repository micronaut-projects/micronaut-micrometer, pull requests merged in 2024-01, with the labels that each got.

#660 [micrometer] Update common files for branch master
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#664 Fixes binary incompatibility changes introduced in #648
  config/accepted-api-changes.json
  micrometer-registry-cloudwatch/src/main/java/io/micronaut/configuration/metrics/micrometer/cloudwatch/CloudWatchMeterRegistryFactory.java
  micrometer-registry-cloudwatch/src/test/groovy/io/micronaut/configuration/metrics/micrometer/cloudwatch/CloudwatchRegistryFactorySpec.groovy
Labels: type: bug

#675 Upate dependencies
  gradle.properties
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#382 add option to skip client side uris
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/ClientRequestMetricRegistryFilter.java
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/ServerRequestMeterRegistryFilter.java
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/WebMetricsPublisher.java
  micrometer-core/src/test/groovy/io/micronaut/configuration/metrics/binder/web/HttpMetricsSpec.groovy
Labels: type: improvement

#678 Add docs for client-errors-uris.enabled configuration
  src/main/docs/guide/metricsConcepts.adoc
Labels: type: docs
