Repository micronaut-projects/micronaut-micrometer, pull requests merged in 2024-05, with the labels that each got.

#753 Build more tags using method context
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/aggregator/AbstractMethodTagger.java
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/executor/ExecutorServiceMetricsBinder.java
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/micrometer/intercept/CountedInterceptor.java
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/micrometer/intercept/TimedInterceptor.java
  micrometer-core/src/test/groovy/io/micronaut/configuration/metrics/annotation/CountedAnnotationSpec.groovy
  micrometer-core/src/test/groovy/io/micronaut/configuration/metrics/annotation/TimeAnnotationSpec.groovy
  micrometer-core/src/test/groovy/io/micronaut/docs/MethodNameTagger.java
  micrometer-core/src/test/java/io/micronaut/configuration/metrics/aggregator/IncorrectMethodTaggerExample.java
  micrometer-core/src/test/java/io/micronaut/configuration/metrics/aggregator/MethodTaggerExample.java
  micrometer-core/src/test/java/io/micronaut/configuration/metrics/aggregator/MethodTaggerExample2.java
  src/main/docs/guide/metricsAnnotations.adoc
Labels: type: enhancement

#762 [micrometer] Update common files for branch 5.6.x
  .github/workflows/gradle.yml
Labels: relates-to: build

#729 Add micronaut-micrometer-registry-otlp binding for micrometer-registry-otlp
  gradle/libs.versions.toml
  micrometer-registry-otlp/build.gradle
  micrometer-registry-otlp/src/main/java/io/micronaut/configuration/metrics/micrometer/otlp/OtlpMeterRegistryFactory.java
  micrometer-registry-otlp/src/main/java/io/micronaut/configuration/metrics/micrometer/otlp/package-info.java
  micrometer-registry-otlp/src/test/groovy/io/micronaut/configuration/metrics/micrometer/otlp/OtlpMeterRegistryFactorySpec.groovy
  micrometer-registry-otlp/src/test/resources/logback.xml
  settings.gradle
  src/main/docs/guide/metricsAndReporters/metricsAndReportersOtlp.adoc
  src/main/docs/guide/toc.yml
Labels: type: enhancement

#740 Adding support for histograms
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/HttpHistogramMeterFilterFactory.java
  micrometer-core/src/test/groovy/io/micronaut/configuration/metrics/binder/web/HttpMetricsSpec.groovy
Labels: type: enhancement

#766 Improvements to the HttpMeterFilterFactory
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/HttpHistogramMeterFilterFactory.java
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/HttpMeterFilterFactory.java
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/config/HttpClientMeterConfig.java
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/config/HttpMeterConfig.java
  micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/config/HttpServerMeterConfig.java
  micrometer-core/src/test/groovy/io/micronaut/configuration/metrics/binder/web/HttpMetricsSpec.groovy
  src/main/docs/guide/metricsConcepts.adoc
Labels: type: improvement
