Repository micronaut-projects/micronaut-micrometer, pull requests merged in 2025-01, with the labels that each got.

#888 [micrometer] Update common files for branch 5.10.x
  .github/workflows/gradle.yml
  buildSrc/build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.micrometer-module.gradle
  gradle/libs.versions.toml
  micrometer-registry-otlp/build.gradle
  micrometer-registry-stackdriver/build.gradle
Labels: relates-to: build

#921 Integrate Micronaut Data and Micrometer to enable tracing SQL queries
  gradle/libs.versions.toml
  micrometer-observation-datasource/build.gradle
  micrometer-observation-datasource/src/main/java/io/micronaut/micrometer/observation/datasource/DataSourceBeanCreatedEventListener.java
  micrometer-observation-datasource/src/main/java/io/micronaut/micrometer/observation/datasource/ObservationDataSourceConfig.java
  micrometer-observation-datasource/src/main/java/io/micronaut/micrometer/observation/datasource/ObservationDataSourceFactory.java
  micrometer-observation-datasource/src/main/java/io/micronaut/micrometer/observation/datasource/ProxyDataSourceResolver.java
  micrometer-observation-datasource/src/main/java/io/micronaut/micrometer/observation/datasource/package-info.java
  micrometer-observation-datasource/src/test/groovy/io/micronaut/micrometer/observation/datasource/MicrometerObservationDataSourceSpec.groovy
  micrometer-observation-datasource/src/test/groovy/io/micronaut/micrometer/observation/datasource/Product.java
  micrometer-observation-datasource/src/test/groovy/io/micronaut/micrometer/observation/datasource/ProductRepository.java
  micrometer-observation-datasource/src/test/resources/logback-test.xml
  settings.gradle
  src/main/docs/guide/datasourceObservation.adoc
  src/main/docs/guide/toc.yml
  test-suite/test-observation-datasource/build.gradle
  test-suite/test-observation-datasource/src/test/java/io/micronaut/micrometer/observation/datasource/MicronautObservationDataSourceTest.java
  test-suite/test-observation-datasource/src/test/java/io/micronaut/micrometer/observation/datasource/Product.java
  test-suite/test-observation-datasource/src/test/java/io/micronaut/micrometer/observation/datasource/ProductRepository.java
  test-suite/test-observation-datasource/src/test/resources/application.properties
  test-suite/test-observation-datasource/src/test/resources/logback.xml
Labels: type: enhancement

#923 Fix reference path in docs
  src/main/docs/guide/metricsAnnotations.adoc
Labels: type: bug
